// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Carbon:add': typeof import('~icons/carbon/add')['default']
    'Carbon:close': typeof import('~icons/carbon/close')['default']
    'Carbon:email': typeof import('~icons/carbon/email')['default']
    'Carbon:filterRemove': typeof import('~icons/carbon/filter-remove')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'Carbon:menu': typeof import('~icons/carbon/menu')['default']
    'Carbon:moon': typeof import('~icons/carbon/moon')['default']
    'Carbon:search': typeof import('~icons/carbon/search')['default']
    'Carbon:sortAscending': typeof import('~icons/carbon/sort-ascending')['default']
    'Carbon:sortDescending': typeof import('~icons/carbon/sort-descending')['default']
    'Carbon:sum': typeof import('~icons/carbon/sum')['default']
    'Carbon:sun': typeof import('~icons/carbon/sun')['default']
    CarbonAdd: typeof import('~icons/carbon/add')['default']
    CarbonClose: typeof import('~icons/carbon/close')['default']
    CarbonEmail: typeof import('~icons/carbon/email')['default']
    CarbonFilterRemove: typeof import('~icons/carbon/filter-remove')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMenu: typeof import('~icons/carbon/menu')['default']
    CarbonSearch: typeof import('~icons/carbon/search')['default']
    'Mdi:qrcodePlus': typeof import('~icons/mdi/qrcode-plus')['default']
    'Mdi:qrcodeRemove': typeof import('~icons/mdi/qrcode-remove')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
