// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Carbon:add': typeof import('~icons/carbon/add')['default']
    'Carbon:book': typeof import('~icons/carbon/book')['default']
    'Carbon:cafe': typeof import('~icons/carbon/cafe')['default']
    'Carbon:chevronLeft': typeof import('~icons/carbon/chevron-left')['default']
    'Carbon:chevronRight': typeof import('~icons/carbon/chevron-right')['default']
    'Carbon:close': typeof import('~icons/carbon/close')['default']
    'Carbon:email': typeof import('~icons/carbon/email')['default']
    'Carbon:filterRemove': typeof import('~icons/carbon/filter-remove')['default']
    'Carbon:idea': typeof import('~icons/carbon/idea')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'Carbon:logoTwitter': typeof import('~icons/carbon/logo-twitter')['default']
    'Carbon:menu': typeof import('~icons/carbon/menu')['default']
    'Carbon:moon': typeof import('~icons/carbon/moon')['default']
    'Carbon:overflowMenuHorizontal': typeof import('~icons/carbon/overflow-menu-horizontal')['default']
    'Carbon:search': typeof import('~icons/carbon/search')['default']
    'Carbon:sun': typeof import('~icons/carbon/sun')['default']
    'Carbon:toolsAlt': typeof import('~icons/carbon/tools-alt')['default']
    'Mdi:chevronDoubleLeft': typeof import('~icons/mdi/chevron-double-left')['default']
    'Mdi:chevronDoubleRight': typeof import('~icons/mdi/chevron-double-right')['default']
    'Mdi:imageRefreshOutline': typeof import('~icons/mdi/image-refresh-outline')['default']
    'Mdi:qrcodePlus': typeof import('~icons/mdi/qrcode-plus')['default']
    'Mdi:qrcodeRemove': typeof import('~icons/mdi/qrcode-remove')['default']
    'Ri:wechat2Fill': typeof import('~icons/ri/wechat2-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
